import { Data, IProductInput } from "@/types";
import { toSlug } from "./utils";

const products: IProductInput[] = [
  // T-Shirts
  {
    name: "Nike Mens Slim-fit Long-Sleeve T-Shirt",
    slug: toSlug("Nike Mens Slim-fit Long-Sleeve T-Shirt"),
    category: "T-Shirts",
    images: ["/images/p11-1.jpg", "/images/p11-2.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 21.8,
    listPrice: 0,
    brand: "Nike",
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 9,
    countInStock: 11,
    description:
      "İnsan sağlığına ve çevreye zarar vermeyen kimyasallar kullanılarak üretilmiştir.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Beyaz", "Kırmızı", "Siyah"],

    reviews: [],
  },
  {
    name: "Jerzees Long-Sleeve Heavyweight Blend T-Shirt",
    slug: toSlug("Jerzees Long-Sleeve Heavyweight Blend T-Shirt"),
    category: "T-Shirts",
    images: [
      "/images/p12-1.jpg",
      "/images/p12-2.jpg",
      "/images/p12-3.jpg",
      "/images/p12-4.jpg",
    ],
    tags: ["featured"],
    isPublished: true,
    price: 23.78,
    listPrice: 0,
    brand: "Jerzees",
    avgRating: 4.2,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 29,
    countInStock: 12,
    description:
      "Sürdürülebilir kaynaklanan Amerika Birleşik Devletleri tarafından yetiştirilen pamuk; Kol-kol arası bant; çift-ayaklı ön yaka; Set-in kol; Gizli dikişli yaka kıyafetleri; Geniş baskı alanı için kabiliyetli gövde",

    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Sarı", "Kırmızı", "Siyah"],

    reviews: [],
  },
  {
    name: "Jerzees Men's Long-Sleeve T-Shirt",
    slug: toSlug("Jerzees Men Long-Sleeve T-Shirt"),
    category: "T-Shirts",
    brand: "Jerzees",
    images: ["/images/p13-1.jpg", "/images/p13-2.jpg"],
    tags: ["best-seller"],
    isPublished: true,
    price: 13.86,
    listPrice: 16.03,
    avgRating: 4,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 55,
    countInStock: 13,
    description:
      "Jerzees uzun kollu t-shirt, dri-power teknolojisiyle üretilmiştir. Bu teknoloji, nemin hapsolmasını sağlayarak günün her anında sıcak ve kuru kalmanıza olanak tanır. Ayrıca, ekstra dayanıklılık için rib kol ve yaka kısmı da dahil edilmiştir. Eğer birçok mevsim için kullanılabilir bir kıyafet arıyorsanız, o zaman daha fazla arama yapmayın.",
    sizes: ["XL", "XXL"],
    colors: ["Yeşil", "Beyaz"],

    reviews: [],
  },
  {
    name: "Decrum Mens Plain Long Sleeve T-Shirt - Comfortable Soft Fashion V Neck Full Sleeves Jersey Shirts",
    slug: toSlug(
      "Decrum Mens Plain Long Sleeve T-Shirt - Comfortable Soft Fashion V Neck Full Sleeves Jersey Shirts"
    ),
    category: "T-Shirts",
    brand: "Jerzees",
    images: ["/images/p14-1.jpg", "/images/p14-2.jpg"],
    tags: ["todays-deal"],
    isPublished: true,
    price: 26.95,
    listPrice: 46.03,
    avgRating: 3.85,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 54,
    countInStock: 14,
    description:
      "Buftunuzu buftunuzla geliştirin. Bu uzun kollu t-shirt, sıradan pamuk t-shirtinizden en üst seviyeye taşıyor.",
    sizes: ["XL", "XXL"],
    colors: ["Sarı", "Beyaz"],

    reviews: [],
  },
  {
    name: "Muscle Cmdr Men's Slim Fit Henley Shirt Long&Short Business Sleeve Casual 3 Metal Buton Placket Casual Stylish T-Shirt",
    slug: toSlug(
      "Muscle Cmdr Men's Slim Fit Henley Shirt Long&Short Business Sleeve Casual 3 Metal Buton Placket Casual Stylish T-Shirt"
    ),
    category: "T-Shirts",
    brand: " Muscle Cmdr",
    images: ["/images/p15-1.jpg", "/images/p15-2.jpg"],
    tags: ["new-arrival", "featured"],
    isPublished: true,
    price: 29.99,
    listPrice: 35.99,
    avgRating: 3.66,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 54,
    countInStock: 15,
    description:
      "İnce Kesim Tasarım: Erkek Kas İnce Kesim Düğmeli Henley Gömlekleri, vücudunuza tam oturacak şekilde tasarlanmıştır, kaslarınızı vurgular ve her ortam için mükemmel olan şık bir siluet oluşturur.",
    sizes: ["XL", "XXL"],
    colors: ["Yeşil", "Sarı"],

    reviews: [],
  },
  {
    name: "Hanes Mens Long Sleeve Beefy Henley Shirt",
    slug: toSlug("Hanes Mens Long Sleeve Beefy Henley Shirt"),
    category: "T-Shirts",
    brand: "Jerzees",
    images: ["/images/p16-1.jpg", "/images/p16-2.jpg"],
    tags: ["best-seller", "todays-deal"],
    isPublished: true,
    price: 25.3,
    listPrice: 32.99,
    avgRating: 3.46,
    numReviews: 13,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 3 },
    ],
    countInStock: 16,
    numSales: 56,
    description:
      "Ağırlıklı pamuk (Heathers 60% pamuk/40% polyester; Pebblestone 75% pamuk/25% polyester)",
    sizes: ["XL", "XXL"],
    colors: ["Gri", "Beyaz"],

    reviews: [],
  },
  // Jeans
  {
    name: "Silver Jeans Co. Mens Jace Slim Fit Bootcut Jeans",
    slug: toSlug("Silver Jeans Co. Mens Jace Slim Fit Bootcut Jeans"),
    category: "Jeans",
    brand: "Silver Jeans Co",
    images: ["/images/p21-1.jpg", "/images/p21-2.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 95.34,
    listPrice: 0,
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    countInStock: 54,
    numSales: 21,
    description:
      "Silver Jeans Co. Jace Slim Fit Bootcut Jeans - Jace, modern cowboy jean olarak düşünün. Aşağıda omurga ve hip ve bilek bölgesinde ince bir fit ile bitirilmiştir. 18\" bootcut leg opening ile daha ince görünümünü tamamlarken, büyük botların üzerinde de uyum sağlar",
    sizes: [ "36Wx30L"],
    colors: ["Mavi", "Gri"],

    reviews: [],
  },
  {
    name: "Levi's mens 505 Regular Fit Jeans (Also Available in Big & Tall)",
    slug: toSlug(
      "Levi's mens 505 Regular Fit Jeans (Also Available in Big & Tall)"
    ),
    category: "Jeans",
    brand: "Levi's",
    images: ["/images/p22-1.jpg", "/images/p22-2.jpg"],
    tags: ["featured"],
    isPublished: true,
    price: 59.99,
    listPrice: 69.99,
    avgRating: 4.2,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 22,
    numSales: 54,
    description: "Birçok mevsim için kullanılabilir bir kıyafet, bu 505.",
    sizes: ["30Wx30L", "34Wx30L", "36Wx30L"],
    colors: ["Mavi", "Gri"],

    reviews: [],
  },
  {
    name: "Essentials Mens Straight-Fit Stretch Jean",
    slug: toSlug("Essentials Mens Straight-Fit Stretch Jean"),
    category: "Jeans",
    brand: "Essentials",
    images: ["/images/p23-1.jpg", "/images/p23-2.jpg"],
    tags: ["best-seller"],
    isPublished: true,
    price: 38.9,
    listPrice: 45,
    avgRating: 4,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 23,
    numSales: 54,
    description:
      "Bu klasik 5-pocket straight-fit jeans, ekstra rahatlık ve şekil koruma için biraz esneklik içerir",
    sizes: ["30Wx30L", "34Wx30L", "36Wx30L"],
    colors: ["Gri", "Mavi"],

    reviews: [],
  },
  {
    name: "Buffalo David Bitton Mens Men's Driven Relaxed Denim JeansJeans",
    slug: toSlug(
      "Buffalo David Bitton Mens Men's Driven Relaxed Denim JeansJeans"
    ),
    category: "Jeans",
    brand: "Buffalo David Bitton",
    images: ["/images/p24-1.jpg", "/images/p24-2.jpg"],
    tags: ["todays-deal"],
    isPublished: true,
    price: 69.99,
    listPrice: 100,
    avgRating: 3.85,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 24,
    numSales: 53,
    description:
      "Stretch recycled denim jeans in an authentic and sanded wash blue. Features a comfortable low-rise waist with a relaxed fit at the leg. The distressed look gives these jeans an effortlessly worn-in feel. The eco-friendly logo patch in tan and red is at the back waistband. The signature maple leaf graphic is debossed at the zip-fly.",
    sizes: ["30Wx30L", "34Wx30L", "36Wx30L"],
    colors: ["Mavi", "Gri"],

    reviews: [],
  },
  {
    name: "Dickies Mens Relaxed Fit Carpenter Jean",
    slug: toSlug("Dickies Mens Relaxed Fit Carpenter Jean"),
    category: "Jeans",
    brand: "Dickies",
    images: ["/images/p25-1.jpg", "/images/p25-2.jpg"],
    tags: ["new-arrival", "featured"],
    isPublished: true,
    price: 95.34,
    listPrice: 0,
    avgRating: 3.66,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 25,
    numSales: 48,
    description:
      "Rahat çalışma jean, eski carpentry-stil çalışma çantası ve logo çalışma çantası",
    sizes: ["30Wx30L", "34Wx30L", "36Wx30L"],
    colors: ["Mavi", "Gri"],

    reviews: [],
  },
  {
    name: "Wrangler mens Premium Performance Cowboy Cut Slim Fit Jean",
    slug: toSlug("Wrangler mens Premium Performance Cowboy Cut Slim Fit Jean"),
    category: "Jeans",
    brand: "Wrangler",
    images: ["/images/p26-1.jpg", "/images/p26-2.jpg"],
    tags: ["best-seller", "todays-deal"],
    isPublished: true,
    price: 81.78,
    listPrice: 149.99,
    avgRating: 3.46,
    numReviews: 13,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 3 },
    ],
    countInStock: 26,
    numSales: 48,
    description:
      "İşlevsel bir fit için tasarlanmıştır, bu jeanlar sizin en sevdiğiniz çift botlarınızın üzerine yığılır. Düşük omurga, koltuk ve bilek bölgesinde ince bir fit ile yapılmıştır, bu jean hem işlev hem de rahatlık için uzun günler için yapılmıştır.",
    sizes: ["30Wx30L", "34Wx30L", "36Wx30L"],
    colors: ["Mavi", "Gri"],

    reviews: [],
  },
  // Watches
  {
    name: "Seiko Men's Analogue Watch with Black Dial",
    slug: toSlug("Seiko Men's Analogue Watch with Black Dial"),
    category: "Wrist Watches",
    brand: "Seiko",
    images: ["/images/p31-1.jpg", "/images/p31-2.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 530.0,
    listPrice: 0,
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    countInStock: 31,
    numSales: 48,
    description:
      "Kasalı: Stentanlı kasalı, yuvarlak kasalı, gri cam: Hardlex, kasalı tip: kasalı, kasalı",
    sizes: [],
    colors: [],

    reviews: [],
  },
  {
    name: "SEIKO 5 Sport SRPJ83 Beige Dial Nylon Automatic Watch, Beige, Automatic Watch",
    slug: toSlug(
      "SEIKO 5 Sport SRPJ83 Beige Dial Nylon Automatic Watch, Beige, Automatic Watch"
    ),
    category: "Wrist Watches",
    brand: "Seiko",
    images: ["/images/p32-1.jpg", "/images/p32-2.jpg"],
    tags: ["featured"],
    isPublished: true,
    price: 375.83,
    listPrice: 400,
    avgRating: 4.2,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 32,
    numSales: 48,
    description:
      "Seiko 5 Sporlarının koleksiyonu, vintage alan/aviator stili: otomatik, manuel sarkıtma yeteneği",
    sizes: [],
    colors: [],

    reviews: [],
  },
  {
    name: "Casio Men's Heavy Duty Analog Quartz Stainless Steel Strap, Silver, 42 Casual Watch ",
    slug: toSlug(
      "Casio Men's Heavy Duty Analog Quartz Stainless Steel Strap, Silver, 42 Casual Watch"
    ),
    category: "Wrist Watches",
    brand: "Casio",
    images: ["/images/p33-1.jpg", "/images/p33-2.jpg"],
    tags: ["best-seller"],
    isPublished: true,
    price: 60.78,
    listPrice: 0,
    avgRating: 4,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 33,
    numSales: 48,
    description:
      "Casio koleksiyonu, bu model MWA-100H-1AVEF ile büyüyor. Stentanlı bir kasalı ile, her günlük şoklara dayanıklı olacaktır.",
    sizes: [],
    colors: [],

    reviews: [],
  },
  {
    name: "Casio Classic Silver-Tone Stainless Steel Band Date Indicator Watch",
    slug: toSlug(
      "Casio Classic Silver-Tone Stainless Steel Band Date Indicator Watch"
    ),
    category: "Wrist Watches",
    brand: "Casio",
    images: ["/images/p34-1.jpg", "/images/p34-2.jpg"],
    tags: ["todays-deal"],
    isPublished: true,
    price: 34.22,
    listPrice: 54.99,
    avgRating: 3.85,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 34,
    numSales: 48,
    description:
      "Yeni MTPVD01D-7EV, 50 metre su direnceli stentanlı bir kasalı, beyaz görünümüyle güncellenmiştir. Bu elegans 3 el saat, herhangi bir ortamda mükemmeldir.",
    sizes: [],
    colors: [],

    reviews: [],
  },
  {
    name: "Fossil Men's Grant Stainless Steel Quartz Chronograph Watch",
    slug: toSlug("Fossil Men's Grant Stainless Steel Quartz Chronograph Watch"),
    category: "Wrist Watches",
    brand: "Fossil",
    images: ["/images/p35-1.jpg", "/images/p35-2.jpg"],
    tags: ["new-arrival", "featured"],
    isPublished: true,
    price: 171.22,
    listPrice: 225,
    avgRating: 3.66,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 35,
    numSales: 48,
    description:
      "Süreklilik görünümü ile, gümüş ve mavi görünümü kasalı, mavi güneş yıldızı görünümü ve gümüş görünümü Roma rakamları",
    sizes: [],
    colors: ["Mavi", "Siyah", "Gümüş"],

    reviews: [],
  },
  {
    name: "Fossil Men's Machine Stainless Steel Quartz Watch",
    slug: toSlug("Fossil Men's Machine Stainless Steel Quartz Watch"),
    category: "Wrist Watches",
    brand: "Fossil",
    images: ["/images/p36-1.jpg", "/images/p36-2.jpg"],
    tags: ["best-seller", "todays-deal"],
    isPublished: true,
    price: 158.21,
    listPrice: 229.0,
    avgRating: 3.46,
    numReviews: 13,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 3 },
    ],
    countInStock: 36,
    numSales: 49,
    description:
      "Masculin siyah-siyah, endüstriyel etkilenmiş bir makine saati, sizin günlük görünümünüze yeni, modern bir dokunuş katacaktır. Bu makine saati, stentanlı bir bilek bantı ile üç el hareketi de içerir.",
    sizes: [],
    colors: ["Kahverengi", "Gümüş", "Siyah"],

    reviews: [],
  },
  // Sneakers
  {
    name: "adidas Mens Grand Court 2.0 Training Shoes Training Shoes",
    slug: toSlug("adidas Mens Grand Court 2.0 Training Shoes Training Shoes"),
    category: "Shoes",
    brand: "adidas",
    images: ["/images/p41-1.jpg", "/images/p41-2.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 81.99,
    listPrice: 0,
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    countInStock: 41,
    numSales: 48,
    description:
      "Cloudfoam Comfort sockliner, çokftan ve çokftan, yumuşak, soluk hava geçirgen kumaş",
    sizes: ["8", "9", "10"],
    colors: ["Beyaz", "Siyah", "Gri"],

    reviews: [],
  },
  {
    name: "ziitop Men's Running Walking Shoes Fashion Sneakers Mesh Dress Shoes Business Oxfords Shoes Lightweight Casual Breathable Work Formal Shoes",
    slug: toSlug(
      "ziitop Men's Running Walking Shoes Fashion Sneakers Mesh Dress Shoes Business Oxfords Shoes Lightweight Casual Breathable Work Formal Shoes"
    ),
    category: "Shoes",
    brand: "ziitop",
    images: ["/images/p42-1.jpg", "/images/p42-2.jpg"],
    tags: ["featured"],
    isPublished: true,
    price: 39.97,
    listPrice: 49.96,
    avgRating: 4.2,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 42,
    numSales: 50,
    description:
      "Cloudfoam Comfort sockliner, çokftan ve çokftan, yumuşak, soluk hava geçirgen kumaş",
    sizes: ["8", "9", "10"],
    colors: ["Beige", "Siyah", "Gri"],

    reviews: [],
  },
  {
    name: "Skechers mens Summits High Range Hands Free Slip-in Shoes Work shoe",
    slug: toSlug(
      "Skechers mens Summits High Range Hands Free Slip-in Shoes Work shoe"
    ),
    category: "Shoes",
    brand: "Skechers",
    images: ["/images/p43-1.jpg", "/images/p43-2.jpg"],
    tags: ["best-seller"],
    isPublished: true,
    price: 99.99,
    listPrice: 0,
    avgRating: 4,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 43,
    numSales: 72,
    description:
      "Skechers Hands Free Slip-ins™: Summits - High Range ile rahatlık içinde adım atın. Exklüsif Heel Pillow™, ayakınızı güvenli bir şekilde tutar, bu vegan stil, benzersiz bir Skechers Slip-ins™ çıkış paneli, sabit kemerli bir kumaş üstü içerir",
    sizes: ["8", "9", "10"],
    colors: ["Mavi", "Siyah", "Gri"],

    reviews: [],
  },
  {
    name: "DLWKIPV Mens Running Shoes Tennis Cross Training Sneakers Fashion Non Slip Outdoor Walking Jogging Shoes Mesh Light Flexible Comfortable Breathable Shoes",
    slug: toSlug(
      "DLWKIPV Mens Running Shoes Tennis Cross Training Sneakers Fashion Non Slip Outdoor Walking Jogging Shoes Mesh Light Flexible Comfortable Breathable Shoes"
    ),
    category: "Shoes",
    brand: "DLWKIPV",
    images: ["/images/p44-1.jpg", "/images/p44-2.jpg"],
    tags: ["todays-deal"],
    isPublished: true,
    price: 36.99,
    listPrice: 56.9,
    avgRating: 3.85,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 44,
    numSales: 72,
    description:
      "Tasarım: Mesh vamp, havalandırma. Sol anti-kayma çentik tasarımı, darbe emniyeti ve anti-kayma. Ayak içi geniş ve yumuşak, sizin için iyi bir rahatlık deneyimi sunar",
    sizes: ["8", "9", "10", "11", "12"],
    colors: ["Kahverengi", "Siyah", "Gri"],

    reviews: [],
  },
  {
    name: "ASICS Men's GT-2000 13 Running Shoes",
    slug: toSlug("ASICS Men's GT-2000 13 Running Shoes"),
    category: "Shoes",
    brand: "ASICS",
    images: ["/images/p45-1.jpg", "/images/p45-2.jpg"],
    tags: ["new-arrival", "featured"],
    isPublished: true,
    price: 179.95,
    listPrice: 200,
    avgRating: 3.66,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 45,
    numSales: 64,
    description:
      "En az %50'si, çöp ve karbon emisyonunu azaltmak için çıkış malzemesiyle yapılmıştır",
    sizes: ["8", "9", "10", "11"],
    colors: ["Mavi", "Siyah", "Gri"],

    reviews: [],
  },
  {
    name: "Mens Wearbreeze Shoes, Urban - Ultra Comfortable Shoes, Breeze Shoes for Men, Men's Mesh Dress Sneakers Business Shoes",
    slug: toSlug(
      "Mens Wearbreeze Shoes, Urban - Ultra Comfortable Shoes, Breeze Shoes for Men, Men's Mesh Dress Sneakers Business Shoes"
    ),
    category: "Shoes",
    brand: "Generic",
    images: ["/images/p46-1.jpg", "/images/p46-2.jpg"],
    tags: ["best-seller", "todays-deal"],
    isPublished: true,
    price: 32.99,
    listPrice: 80,
    avgRating: 3.46,
    numReviews: 13,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 3 },
    ],
    countInStock: 46,
    numSales: 48,
    description:
      "Cloudfoam Comfort sockliner, çokftan ve çokftan, yumuşak, soluk hava geçirgen kumaş",
    sizes: ["8", "9", "10", "11"],
    colors: ["Yeşil", "Siyah", "Gri"],

    reviews: [],
  },
];

const data: Data = {
  headerMenus: [
    {
      name: "Günün Fırsatı",
      href: "/search?tag=todays-deal",
    },
    {
      name: "Yeni Gelenler",
      href: "/search?tag=new-arrival",
    },
    {
      name: "Öne Çıkan Ürünler",
      href: "/search?tag=featured",
    },
    {
      name: "En Çok Satanlar",
      href: "/search?tag=best-seller",
    },
    {
      name: "Gezinme Geçmişi",
      href: "/#browsing-history",
    },
    {
      name: "Müşteri Hizmetleri",
      href: "/page/customer-service",
    },
    {
      name: "Hakkımızda",
      href: "/page/about-us",
    },
    {
      name: "Yardım",
      href: "/page/help",
    },
  ],

  carousels: [
    {
      title: "Popüler 3D Maketler",
      buttonCaption: "Görüntüle",
      image: "/images/banner3.jpg",
      url: "/search?category=Shoes",
      isPublished: true,
    },
    {
      title: "Hayallerinizdeki Görselin 3D Maketini Alın",
      buttonCaption: "Görüntüle",
      image: "/images/banner1.jpg",
      url: "/search?category=T-Shirts",
      isPublished: true,
    },
    {
      title: "3D Maketlerimiz",
      buttonCaption: "Görüntüle",
      image: "/images/banner2.jpg",
      url: "/search?category=Wrist Watches",
      isPublished: true,
    },
  ],

  products,
};

export default data;
